name: Welcome file
on: 
  pull_request: 
    types: [opened]
jobs:
  build:
    name: build Job
    runs-on: ubuntu-latest
    steps:
      -run: gh pr comment $PR_URL --body "My new pull request using workflow"
       env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
      
